scrape_configs:
  - job_name: 'node_service_discovery'
    file_sd_configs:
      - files:
        - targets/*.json
        refresh_interval: 60m
      - files:
        refresh_interval: 60m	
        - targets/*.yaml